model = "Qwen/Qwen3-0.6B"

[env]
id = "unboxer"

[env.args]
max_turns = 20
use_remote = false
train_step = 0
migrate = true

[inference]
gpus = 1

[inference.args]
enforce_eager = true
tensor_parallel_size = 1

[trainer]
gpus = 1

[trainer.args]
run_name = "unboxer-qwen3-0.6b"
micro_batch_size = 2
rollouts_per_example = 8
batch_size = 64
max_steps = 1000
max_seq_len = 4096
max_tokens = 512
learning_rate = 5e-5
use_lora = true
